name: ci

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - 'main'

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Set Version
      run: mvn versions:set -DnewVersion=${GITHUB_REF##*/}-SNAPSHOT

    - name: mvn verify
      run: mvn clean verify

    - name: package
      run: mvn -B package --file pom.xml

    - name: deploy
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}