name: ci

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Set Version
        run: |
          BRANCH_NAME=$(echo ${GITHUB_REF##*/} | sed 's/[\/]/-/g' | sed 's/[^a-zA-Z0-9.-]//g')
          mvn versions:set -DnewVersion=1.0-${BRANCH_NAME}-SNAPSHOT

      - name: package
        run: mvn -B package --file pom.xml

      - name: deploy
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}