name: release
on:
  push:
    tags:
      - 'release/[0-9]+.[0-9]+.[0-9]+'
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Prepare
        id: prepare
        run: |
         echo "VERSION=${GITHUB_REF#refs/tags/release/}" >> GITHUB_ENV # Removes 'refs/tags/release/' prefix
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Set up JDK 21
        id: setup_java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
      - name: Set Version
        id: set_version
        run: mvn versions:set -DnewVersion=${VERSION}
      - name: Package
        id: package
        run: mvn -B package --file pom.xml
      - name: Deploy
        id: deploy
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ VERSION }}
          release_name: Release ${{ VERSION }}
          body: |
            This is an automatically generated release.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}