name: release
on:
  push:
    tags:
      - 'release/[0-9]+.[0-9]+.[0-9]+'
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Extract version from tag
        id: extract_version
        run: |
          if [[ "$GITHUB_REF" =~ refs/tags/release/([0-9]+\.[0-9]+\.[0-9]+) ]]; then
            echo "VERSION=${BASH_REMATCH[1]}" >> $GITHUB_ENV
            echo "Extracted Version: ${{ env.VERSION }}"
          else
            echo "Tag name does not match expected format 'release/x.y.z'" >&2
            exit 1
          fi
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Set up JDK 21
        id: setup_java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}
      - name: Set Version
        id: set_version
        run: mvn versions:set -DnewVersion=${VERSION}
      - name: Package
        id: package
        run: mvn -B package --file pom.xml
      - name: Deploy
        id: deploy
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          body: |
            This is an automatically generated release.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}