name: release

on:
  push:
    tags:
      - 'release/[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Set Version
        run: |
          FULL_TAG_NAME=${GITHUB_REF#refs/tags/} # Removes 'refs/tags/' prefix
          SANITIZED_TAG_NAME=$(echo $FULL_TAG_NAME | sed 's/[\/]/-/g') # Replace slashes with hyphens
          mvn versions:set -DnewVersion=${SANITIZED_TAG_NAME}-SNAPSHOT

      - name: package
        run: mvn -B package --file pom.xml

      - name: deploy
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}
