name: ci

on:
  pull_request:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set Version
        run: mvn versions:set -DnewVersion=${GITHUB_REF##*/}-SNAPSHOT

      - name: package
        run: mvn -B package --file pom.xml